Repository CSID-DGU/2024-02-CSC4004-2-4-Bullsazoo, pull requests merged in 2024-12, with the labels that each got.

#25 [fix] user 모델 수정
  backend/backend/user/urls.py
  backend/backend/user/utils.py
  backend/backend/user/views.py
Labels: fix

#30 [feat] Yolov5 1&2차 학습 기록
  backend/yolov5/training_result_2
Labels: feat

#33 [feat] Yolov5 3차 학습 기록
  backend/yolov5/training_result_3
Labels: feat

#35 [fix] 디렉토리 구조 변경
  backend/.env
  backend/Dockerfile
  backend/backend/settings.py
  backend/backend/test/yolov5/training_result_2
  backend/backend/urls.py
  backend/backend/user/views.py
  backend/requirements.txt
Labels: fix

#43 [feat] backend 모델 수정 및 추가
  .github/PULL_RESQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .gitignore
  backend/analyze/__init__.py
  backend/analyze/admin.py
  backend/analyze/apps.py
  backend/analyze/migrations/__init__.py
  backend/analyze/models.py
  backend/analyze/serializers.py
  backend/analyze/tests.py
  backend/analyze/urls.py
  backend/analyze/views.py
  backend/analyze/yolov5_handler.py
  backend/backend/__pycache__/__init__.cpython-312.pyc
  backend/backend/__pycache__/settings.cpython-312.pyc
  backend/backend/__pycache__/urls.cpython-312.pyc
  backend/backend/api/gpt/gpt_text_generator.py
  backend/backend/api/stt_tts/Senarios/Scripts/Description.txt
  backend/backend/api/stt_tts/Senarios/Scripts/Login.txt
  backend/backend/api/stt_tts/Senarios/Scripts/Signin.txt
  backend/backend/api/stt_tts/Senarios/__init__.py
  backend/backend/api/stt_tts/Senarios/mp3/Description.mp3
  backend/backend/api/stt_tts/Senarios/mp3/Login.mp3
  backend/backend/api/stt_tts/Senarios/mp3/Signin.mp3
  backend/backend/api/stt_tts/__init__.py
  backend/backend/api/stt_tts/config.json
  backend/backend/api/stt_tts/stt_handler.py
  backend/backend/api/stt_tts/tts_handler.py
  backend/backend/api/stt_tts/utils/__init__.py
  backend/backend/api/stt_tts/utils/credentials.py
  backend/backend/features/command_recognition/__init__.py
  backend/backend/features/command_recognition/command_recognition_realtime.py
  backend/backend/features/object_recognition/__init__.py
  backend/backend/objects_recognition_realtime.py
  backend/backend/settings.py
  backend/backend/test/yolov5/classify/tutorial.ipynb
  backend/backend/test/yolov5/segment/tutorial.ipynb
  backend/backend/test/yolov5/training_result_3
  backend/backend/test/yolov5/tutorial.ipynb
  backend/backend/urls.py
  backend/backend/user/models.py
  backend/backend/user/serializers.py
  backend/backend/user/urls.py
  backend/backend/user/views.py
  backend/manage.py
  backend/user/__init__.py
  backend/user/admin.py
  backend/user/apps.py
  backend/user/asgi.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/tests.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wsgi.py
Labels: feat, fix

#45 [feat] 로그인/회원가입 DB연결
  backend/backend/settings.py
  backend/user/models.py
  backend/user/serializers.py
  backend/user/urls.py
  backend/user/views.py
Labels: feat

#50 [fix] manage.py runserver 오류 해결
  backend/analyze/admin.py
  backend/analyze/migrations/0001_initial.py
  backend/analyze/serializers.py
  backend/analyze/tests.py
  backend/analyze/urls.py
  backend/analyze/views.py
  backend/analyze/yolov5_handler.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/0002_alter_users_options.py
  backend/user/models.py
Labels: fix

#53 [feat] yolov5 이미지 분석 기능 완료
  backend/analyze/urls.py
  backend/analyze/yolov5_handler.py
  backend/backend/settings.py
  backend/backend/test/yolov5/classes.txt
  backend/user/migrations/0001_initial.py
  backend/user/migrations/0002_alter_users_options.py
Labels: feat

#59 [fix] - #58 - requirements.txt 수정
  backend/requirements.txt
Labels: fix

#61 [feat] 로그인/회원가입 페이지 최신화/ swagger까지 최신화(작업중)
  backend/analyze/urls.py
  backend/analyze/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/user/admin.py
Labels: feat

#63 [feat] 로그인/회원가입 페이지 최신화/ swagger까지 최신화/ yolov5 reponse body 및 물체인식 정상(작업중
  backend/analyze/admin.py
  backend/analyze/models.py
  backend/analyze/serializers.py
  backend/analyze/views.py
  backend/analyze/yolov5_handler.py
Labels: feat

#64 [feat] 앱 analyze swagger테스트 완료
  backend/analyze/models.py
  backend/analyze/urls.py
  backend/backend/settings.py
Labels: feat

#70 [fix] 데이터베이스 HOST IP주소 변경
  backend/backend/settings.py
Labels: fix

#77 ip 수정
  backend/backend/settings.py
Labels: fix

#81 [fix] 물체인식 기능 구현 테스트 수정 및 완료
  backend/analyze/admin.py
  backend/analyze/apps.py
  backend/analyze/migrations/0001_initial.py
  backend/analyze/models.py
  backend/analyze/serializers.py
  backend/analyze/tests.py
  backend/analyze/urls.py
  backend/analyze/views.py
  backend/analyze/yolov5_handler.py
  backend/backend/settings.py
Labels: fix

#82 [feat] 로그인/회원가입 테스트 완료
  backend/user/models.py
  backend/user/serializers.py
  backend/user/views.py
Labels: feat

#87 [fix] 물체 기능 구현 수정(media의 이미지로 인식)
  backend/analyze/views.py
  backend/media/uploads/please.jpg
Labels: fix
